fix(#18): beans classes not found at runtime
Crash log reported:

Build Type: debug
SDK: 35
Android: 15
Model: M346BXXS8DYH1
Base OS: samsung/m31inn/m34x:15/AP3A.240905.015.A2/M346BXXU7DYE1:user/release-keys
SUPPORTED_ABIS: [Ljava.lang.String;@1a0d5e9
SUPPORTED_32_BIT_ABIS: [Ljava.lang.String;@dde426e
SUPPORTED_64_BIT_ABIS: [Ljava.lang.String;@ef3fd0f
Manufacturer: samsung
Device External Storage: /storage/emulated/0

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/icst/blockidle/bean/ProjectBean;
at com.icst.blockidle.viewmodel.ProjectConfigurationDialogViewModel.onCreate(ProjectConfigurationDialogViewModel.java:52)
at com.icst.blockidle.databinding.DialogProjectConfigBindingImpl._internalCallbackOnClick(DialogProjectConfigBindingImpl.java:315)
at com.icst.blockidle.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
at android.view.View.performClick(Unknown Source:17)
at android.widget.TextView.performClick(Unknown Source:0)
at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1345)
at android.view.View.performClickInternal(Unknown Source:3)
at android.view.View.-11793Nest(Unknown Source:0)
at android.view.View.run(Unknown Source:8)
at android.os.Handler.handleCallback(Unknown Source:2)
at android.os.Handler.dispatchMessage(Unknown Source:4)
at android.os.Looper.loopOnce(Unknown Source:185)
at android.os.Looper.loop(Unknown Source:34)
at android.app.ActivityThread.main(Unknown Source:107)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit.run(Unknown Source:9)
at com.android.internal.os.ZygoteInit.main(Unknown Source:308)
Caused by: java.lang.ClassNotFoundException: Didn't find class com.icst.blockidle.bean.ProjectBean on path: DexPathList[[zip file /data/app/~~R0AuoCSMP-49_c-4dA5z5g==/com.icst.blockidle-GX4mwrmYfWepqyDOhPN0CQ==/base.apk],nativeLibraryDirectories=[/data/app/~~R0AuoCSMP-49_c-4dA5z5g==/com.icst.blockidle-GX4mwrmYfWepqyDOhPN0CQ==/lib/arm64, /data/app/~~R0AuoCSMP-49_c-4dA5z5g==/com.icst.blockidle-GX4mwrmYfWepqyDOhPN0CQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
... 17 more